//////////////////////////////////////
//////////// POSTEOS ////////////////

### POR ID ###
GET http://localhost:3048/post/88

### BUSCAR POR FILTRO ###
GET http://localhost:3048/posts?filter=santiago

### PAGINACION ###
GET http://localhost:3048/posts/event%20videos


### CREAR POST ###
POST http://localhost:3048/post
Content-Type: application/json; charset=utf-8

{
  "author": "cirqupipa",
  "content": "holGDASDASDASDASDASDASDASDASDASDASDASD",
  "description": "ASDASDASDASDASDASD",
  "tags": "",
  "title": "100%V - ENE ENE - PARANOID - ALB - OVER IT - STREET JAM 2016",
  "type_id": "1",
  "user_id": 21,
  "video_link": "https://www.youtube.com/watch?v=nbH-MqBWoZ4"
}

### ELIMINAR POST POR ID ###
DELETE http://localhost:3048/post/138

### ACTUALIZAR POST POR ID ###
PUT http://localhost:3048/post/55
Content-Type: application/json; charset=utf-8

{
  "title": "GUERRA BMX - Seamus McKeon" ,
  "description": "We're proud to present the long-awaited release of the Moose, Seamus McKeon's signature Guerra frame. Now available at veinbmx.com and finer dealers everywhere. http://www.veinbmx.com/bmx-frames/Gue... For specs and photos, visit www.guerrabmx.com.",
  "content": "Filmed by Phil Jones, Zachery Rogers, Logan Derberry & Stew Johnson. Edited by Logan Derberry & Seamus McKeon.",
  "video_link": "https://www.youtube.com/watch?v=kN61xIhkwLg",
  "tags": "guerra, moose, frame",
  "author": "GUERRA",
  "user_id": 1,
  "type_id": 2
}
### MODIFICAR POST POR ID ###
PATCH  http://localhost:3048/post/162
Content-Type: application/json

{
  "title": "United \" Dont Matter \" ",
  "description": "2007 united video",
  "content": "riders: corey martinez, nathan williams....",
  "tags": "street,2007,united",
  "type_id": "3"
}


//////////////////////////////////////
//////////// USUARIOS ////////////////

### Obtener todos los usuarios (con o sin filtro)
GET http://localhost:3048/users?limit=20&offset=0

### Obtener usuarios con filtro
GET http://localhost:3048/users?filter=ivan&limit=10&offset=0

### Obtener usuario por ID
GET http://localhost:3048/users/1

### Modificar ususario por ID
PATCH http://localhost:3048/users/26
Content-Type: application/json

{
  "favs": "177,184,160,176"
}

### Crear un nuevo usuario
POST http://localhost:3048/users/register
Content-Type: application/json

{
  "email": "jesihola.com",
  "last_name": "u",
  "name": "jesica",
  "user_name": "jesijesi",
  "user_password": "l"
}


### Login ###

POST http://localhost:3048/users/login
Content-Type: application/json

{
  "email": "ivan@prueba.com",
  "user_password": "loramones"
}

### LogOut ### 
POST http://localhost:3048/users/closeSession

### Actualizar usuario completamente (PUT)
PUT http://localhost:3048/users/1
Content-Type: application/json

{
  "user_name": "mer",
  "name": "Iv",
  "last_name": "f",
  "user_password": "mi10",
  "email": "ivan@nucom",
  "user_type": "admin"
}

### Modificar parcialmente un usuario (PATCH)
PATCH http://localhost:3048/users/1
Content-Type: application/json

{
  "email": "ivan@balmersin.com"
}

### Eliminar un usuario
DELETE http://localhost:3048/users/1

### Autenticacion
GET http://localhost:3048/users/auth

//////////////////////////////////////
////////// COMENTARIOS //////////////

### Obtener comentarios por pots id
GET http://localhost:3048/comments/184

### Crear comentarios
POST http://localhost:3048/comments
Content-Type: application/json

{
  "user_id": 22, 
  "post_id": 184,
  "content": "esta mas loco q las cabras!!!"
}

### Actualizas comentarios
PUT http://localhost:3048/comments/50
Content-Type: application/json

{
  "id": 50,
  "content": "está más loco que una cabra 🐐",
  "user_id": 22
}

### Modificar comentarios
PATCH http://localhost:3048/comments/50
Content-Type: application/json

{
  "content": "cambió el comentario 😂"
}


### borrar comentarios por pots id
DELETE  http://localhost:3048/comments/2


